//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.21 at 12:51:10 AM EDT 
//


package com.worldnewsonmap.weather.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.worldnewsonmap.yahooweather.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.worldnewsonmap.yahooweather.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link Query.Results }
     * 
     */
    public Results createQueryResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link Query.Results.Channel }
     * 
     */
    public Channel createQueryResultsChannel() {
        return new Channel();
    }

    /**
     * Create an instance of {@link Query.Results.Channel.Item }
     * 
     */
    public Item createQueryResultsChannelItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Query.Results.Channel.Location }
     * 
     */
    public Location createQueryResultsChannelLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Query.Results.Channel.Units }
     * 
     */
    public Units createQueryResultsChannelUnits() {
        return new Units();
    }

    /**
     * Create an instance of {@link Query.Results.Channel.Wind }
     * 
     */
    public Wind createQueryResultsChannelWind() {
        return new Wind();
    }

    /**
     * Create an instance of {@link Query.Results.Channel.Atmosphere }
     * 
     */
    public Atmosphere createQueryResultsChannelAtmosphere() {
        return new Atmosphere();
    }

    /**
     * Create an instance of {@link Query.Results.Channel.Astronomy }
     * 
     */
    public Astronomy createQueryResultsChannelAstronomy() {
        return new Astronomy();
    }

    /**
     * Create an instance of {@link Query.Results.Channel.Image }
     * 
     */
    public Image createQueryResultsChannelImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Query.Results.Channel.Item.Condition }
     * 
     */
    public Condition createQueryResultsChannelItemCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link Query.Results.Channel.Item.Forecast }
     * 
     */
    public Forecast createQueryResultsChannelItemForecast() {
        return new Forecast();
    }

    /**
     * Create an instance of {@link Query.Results.Channel.Item.Guid }
     * 
     */
    public Guid createQueryResultsChannelItemGuid() {
        return new Guid();
    }

}
